### PR TITLE
Revert "Remove and disable package-lock.json"

### PR DESCRIPTION
**Pull request by nemuzuka**
Master branch is in error state

https://travis-ci.org/markushedvall/node-plantuml/branches

This reverts commit f0d63c9220839417fe6d9283e6e9755166289304.

### CODE REVIEW

**Comment by nemuzuka** [comment]
Even this was useless, so I will withdraw. I'm sorry

**Comment by markushedvall** [comment]
It's the get-plantuml-jar.js that is failing to download the plantuml.jar.
It might be that the path of the jar has changed or there might be some problem with sourceforge.

I will look into it...

**Comment by markushedvall** [comment]
And just to be clear, it only affects new development. The published package is still working.

**Comment by nemuzuka** [comment]
@markushedvall 
Thank you for your reply.
And just to be clear, it only affects new development. The published package is still working.

> The published package is still working.

Because I was concerned that the master branch was in error, I issued a pull request.
Thank you

**Pull request closed without merging**
